function spawnThePlayer (element)
	local x = playerGetElementData(element,"PosX")
	local y = playerGetElementData(element,"PosY")
	local z = playerGetElementData(element,"PosZ")
	local rot = playerGetElementData(element,"Rotation")
	local skin = playerGetElementData(element,"Skin")
	local dim = playerGetElementData(element,"Dimension")
	local int = playerGetElementData(element,"Interior")
	spawnPlayer(element,x,y,z,rot,skin,int,dim)
	setCameraTarget(element,element)
	fadeCamera(element,true)
	showCursor(element,false)
	showChat(element,true)
	showPlayerHudComponent(element,"crosshair",true)
	showPlayerHudComponent(element,"radar",true)
	setPedHeadless(element,true)
end